# -*- coding: utf-8 -*-
"""Week-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1btB-gpKBtN2bgAXNWjbehZSp0zRMv8Pv
"""

print("Please Enter A Number Which is Less Than 7 Always")
print("To Quit The Game Please Press 'Q'")
Fr_Positions = list(["B","B","B","_","G","G","G"])
print(["0","1","2","3","4","5","6"])
print(Fr_Positions)

while True:
    move = input("Please Make Your Move :")



    if move == "Q":
      print("You have quit the game.")    ## If The player wants to quit the game
      break

    move = int(move)                    ## Type casting input into integer data type

    if move<0 or 6<move:
        print("Move Made is Invalid")     ## For number entered which are less than 0 or gretaer than 6
        continue
    if Fr_Positions[move] == "_":
        print("Move Made is Invalid")     ## If the number entered is correct but doesnot have any frog at that location
        continue



    if Fr_Positions[move] == "B":
      if(move+1) <= 6 and Fr_Positions[move+1] == "_":
        pass

      elif (move+2)<=6 and Fr_Positions[move+2]=="_" and Fr_Positions[move+1]=="G":
        pass
                 ## Logic for Brown frogs to jump forward
      else:
        print("Move Made is Invalid")
        break


    if Fr_Positions[move] == "G":

      if(move-1) >= 0 and Fr_Positions[move-1] == "_":
        pass

      elif (move-2)>=0 and Fr_Positions[move-2]=="_" and Fr_Positions[move-1]=="B":
        pass
                 ## Logic for Green frogs to jump forward
      else:
        print("Move Made is Invalid")
        break




    move_2 = 0

    if Fr_Positions[move] == "B":
      if Fr_Positions[move+1] == "_":
        move_2 = move+1
      elif Fr_Positions[move+2] == "_":
        move_2 = move+2
    if Fr_Positions[move] == "G":
      if Fr_Positions[move-1] == "_":
        move_2 = move-1
      elif Fr_Positions[move-2] == "_":
        move_2 = move-2

    Fr_Positions[move], Fr_Positions[move_2] = Fr_Positions[move_2], Fr_Positions[move]




    print(["0","1","2","3","4","5","6"])
    print(Fr_Positions)


    if Fr_Positions == ["G","G","G","_","B","B","B"] :
      print("You have won the Game")
      break

